In [1]:
import numpy as np
import time

In [2]:
arr = np.array([1,2,3,4])
print(arr,type(arr))

[1 2 3 4] <class 'numpy.ndarray'>


In [3]:
size=1_000_000

#python_lists
py_list = list(range(size))
start = time.time()
sq_list = [x **  2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

#numpy arrays
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"numpy_array time = {end-start} seconds")

python list time = 0.18430328369140625 seconds
numpy_array time = 0.0 seconds


In [4]:
#create - from lists
arr = np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype)

arr2 = np.array([1,2,3,4,5, "prime"])
print(arr2,type(arr2),arr2.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'> int32
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U11


In [5]:
#create - from lists
arr = np.array([1,2,3,4,5])
print(arr,type(arr),arr.shape)

arr2 = np.array([1,2,3,4,5, "prime"])
print(arr2,type(arr2),arr2.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)


In [6]:
#matrix

arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#Dimension m*n

arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d.shape)

(3, 3)


In [8]:
arr1 = np.zeros((2,3))
print(arr1,arr1.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)


In [9]:
arr1 = np.zeros((2,3),dtype="int64")
print(arr1,arr1.shape)

[[0 0 0]
 [0 0 0]] (2, 3)


In [10]:
arr1 = np.ones((2,3),dtype="int64")
print(arr1,arr1.shape)

[[1 1 1]
 [1 1 1]] (2, 3)


In [11]:
arr1 = np.ones((2,),dtype="int64")
print(arr1)

[1 1]


In [12]:
arr1 = np.full((3,3),100)
print(arr1,arr1.shape)

[[100 100 100]
 [100 100 100]
 [100 100 100]] (3, 3)


In [13]:
#identity matrix
arr4 = np.eye(3)
print(arr4,arr4.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


In [14]:
#range(start,end,step)
arr5 = np.arange(1,10,2)
print(arr5,arr5.shape)

[1 3 5 7 9] (5,)


In [15]:
#linspace
arr6 = np.linspace(1,100,3)
print(arr6,arr6.shape)

[  1.   50.5 100. ] (3,)


In [16]:
#properties

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.size)#size
print(arr.shape)#dimensions m*n
print(arr.dtype)
print(arr.ndim)#total no of dimensions

float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

9
(3, 3)
int32
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [17]:
#operations

arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped = arr.reshape(3,2)
print(reshaped,reshaped.shape)

flattened = arr.flatten() #2D to 1D
print(flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [18]:
#indexing
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0][1])

2


In [19]:
#fancy indexing
arr = np.array([1,2,3,4,5,6])
idx = [0,1,3]
print(arr[idx])

[1 2 4]


In [20]:
#boolean indexing

arr= np.array([1,2,3,4,5,6])
print(arr[arr>2])
print(arr[arr%2 == 0])
print(arr[arr%2 != 0])

[3 4 5 6]
[2 4 6]
[1 3 5]


In [21]:
#sclicing
arr= np.array([1,2,3,4,5,6])
print(arr[1:4])
print(arr[1:])

[2 3 4]
[2 3 4 5 6]


In [22]:
#copy in list vs view in numpy
#num = [1,2,3,4,5,6]
#sub_list = num[1:3]
#print(sub_list)
#print(num)

num = [1,2,3,4,5,6]
arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3].copy()
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)
print(arr)

[2 3]
[200   3]
[1 2 3 4 5]


In [23]:
#Data types

arr= np.array([1,2,3,4,5])
print(arr,arr.dtype)

arr= np.array([1,2,3.14,4,5])
print(arr,arr.dtype)

arr= np.array([1,2,3.14,4,5, "prime"])
print(arr,arr.dtype)

[1 2 3 4 5] int32
[1.   2.   3.14 4.   5.  ] float64
['1' '2' '3.14' '4' '5' 'prime'] <U32


In [24]:
#complex numbers
arr = np.array([3 + 5j])
print(arr,arr.dtype)

[3.+5.j] complex128


In [25]:
#complex numbers operations
arr1 = np.array([3+2j])
arr2 = np.array([5+7j])
print(arr1+arr2)
print(arr1-arr2)

[8.+9.j]
[-2.-5.j]


In [26]:
#objects
arr= np.array(["prime",3.14,3,{1,2,3}])
print(arr,arr.dtype)

['prime' 3.14 3 {1, 2, 3}] object


In [27]:
#multi- dimensional array
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
sum_of_columns=np.sum(arr2d,axis=0)
print(sum_of_columns)
print(np.sum(arr2d))
print(arr2d[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
45
[[2]
 [5]]


In [28]:
sum_of_columns=np.sum(arr2d,axis=0)
print(sum_of_columns)

[12 15 18]


In [29]:
#3d array

arr3d = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3d,arr3d.shape)

#inexing
print(arr3d[1,1,0])

#slicing
print(arr3d[:,0,:])

arr3d[:,0,:] = 99
print(arr3d)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [30]:
#vectorization

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr1+arr2)

[ 7  9 11 13 15]


In [31]:
#broadcasting
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr1 + arr2)
print(arr.shape)

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
(4,)


In [36]:
#normalize

arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [41]:
#mathematicalfunctions

#aggregation

arr = np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.median(arr))
print(np.argmin(arr))
print(np.argmax(arr))

15
120
1
5
3.0
1.4142135623730951
2.0
3.0
0
4
